### ISSUE TITLE
Incorrect fingerprinting when not using 100% match

### ISSUE THREAD

**Issue by MikeSilvis** [BranchMetrics/ios-branch-deep-linking#355]
We have noticed cases where in our office we have gotten other peoples deep links internally. I believe this is because the SDK falls back to the old matching algorithm if the device is not a fresh install. 

Why is there a 30 day boolean flag as to whether or not you use the safari view controller? I would expect on anything > iOS 9 to only and always use the Safari View Controller approach.

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m#L60

**Comment by aaustin** [comment]
Thanks for the note Mike. Here are some thoughts on the subject.

If the app is previously installed, using Universal Links or URI schemes appropriately will guarantee 100% match since we directly pass the parameters through to the app. It's why we originally inserted the install-only SVC check. Because of this, I'm not totally sure it's because of this 30 day check you reference.

We've recently discovered a bug with Safari that causes multiple outstanding clicks/matches to be created for the same device browser. Basically, if you put a URL in safari and start appending parameters to it with the iOS keyboard, Safari actually prefetches the URL with every change you make to the URL with the Safari user agent and refuses to accept cookies. So, from Branch's perspective, it looks like new humans with new browsers clicking links. Thanks Apple. In this case, it's possible that you queue up a bunch of open matches that unsuspecting office companions could intercept on next open.

With regard to the fresh install case, unfortunately, as you're testing, if you're all on the same wifi/device/version, and someone in the office opens the link before you install the app, it's possible that they receive your params. However, based on your understanding, it sounds like you know it's not this.

**Comment by MikeSilvis** [comment]
Yes, so Universal Links do help with the case that i have the app installed, and I link and that i get the ticket. This is not the issue though. The issue though we are seeing is that someone must be on the same wifi/device/version and is stealing a deep link from someone else.

My main question is, why are you using the matching at all instead of only SVC ? 
```
"With regard to the fresh install case, unfortunately, as you're testing, if you're all on the same wifi/device/version, and someone in the office opens the link before you install the app, it's possible that they receive your params."
```

Why is this at all possible still ? If you only use SVC it would eliminate this.

**Comment by aaustin** [comment]
Ah - the problem arises when the click originates from a non-Safari cookie space. For example, if you click a link from Facebook, Messenger, Gmail, or Twitter just to name the common ones, SVC doesn't apply.

In theory, we could support a don't allow weak matches for previously strong matched browsers, but this makes it super hard to test with, since you might clear your IDFA or be in debug mode or something.

**Comment by MikeSilvis** [comment]
So I guess the issue you are pointing to here is if I use an embedded
browser I.e. Facebook you won't get the cookies from the svc

**Comment by MikeSilvis** [comment]
That makes sense. Okay thanks

**Comment by aaustin** [comment]
@MikeSilvis closing this out. If you want some help debugging your specific test scenario, shoot a note over to support@branch.io. Happy linking!

**Comment by MikeSilvis** [comment]
@aaustin if i submitted a PR, with a flag to force only strong matching, would you guys be willing to merge that feature ?

Basically the issue we are running into, is what we are sending through you guys is extremely secure, and we don't want to run the chance of someone else getting it, and we are okay with you having to potentially tap the link twice (because then universal links would take over and it would be 100%)

**Comment by MikeSilvis** [comment]
Also, i guess my original question wasn't answered as to why exactly there is the 30 day check, and not to always use it with cascading principles.

**Comment by ahmednawar** [comment]
@MikeSilvis you're definitely welcome to submit a PR and we'll review it. 

We already have a boolean flag that we send back with the data to indicate whether the user was 100% matched. It is called +match_guaranteed = 0 or 1. 

The way we use cookie-based matching is that we send a request with the IDFA and the browser cookie to create a link between them. Once this is saved, we use it whenever possible to match the user. The 30 day check is to send this request periodically in case the user changed their IDFA or cleared the cookie so that we can create a new link between them. Hope this clarified. Let me know if you have other questions.
