### ISSUE TITLE
Click on branch link will trigger deep link handler twice

### ISSUE THREAD

**Issue by jay-zhu** [BranchMetrics/ios-branch-deep-linking#361]
When I clicked on branch link, it will trigger deep link hander twice if i have open url logic in deep link handler:
```
Branch *branch = [Branch getInstance];
[branch initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
       if (!error) {
              deeplinkPath = params[@"$deeplink_path"];
              if (deeplinkPath) {
                      [[UIApplication sharedApplication]openURL:[NSURL URLWithString:[NSString stringWithFormat:@"myapp://%@",deeplinkPath]]];
              }
        }
})];
```

And second time when it trigger deep link handler, params are still same, which it will cause another openUrl again.

**Comment by derrickstaten** [comment]
Hi @jay-zhu, there's an easy way to avoid this. Rather than calling `openURL:`, you should instead invoke whatever routing logic you use inside of `application:openURL:sourceApplication:annotation:` directly.

So if `application:openURL:sourceApplication:annotation:` calls `[self handleURL:url];`, then inside the branch initSession callback, you can invoke the same method. `[self handleURL:[NSURL URLWithString:[NSString stringWithFormat:@"myapp://%@",deeplinkPath]]];`. If you haven't already abstracted out this logic into a nice `handleURL:` function, it's fairly simple to do so.

**Comment by jay-zhu** [comment]
@derrickstaten I see. Thank you.

**Comment by derrickstaten** [comment]
No problem, sorry for the confusion.
