### ISSUE TITLE
Branch SDK should include nullability

### ISSUE THREAD

**Issue by joshuafeldman** [BranchMetrics/ios-branch-deep-linking#368]
Since the Branch SDK is written in Objective-C it should contain correct nullability for projects that are Swift. As an example `typedef void (^callbackWithParams) (NSDictionary *params, NSError *error);` will signal to Swift that both `params` and `error` are `nonnull` (default) which is not true. Both these parameters should be marked `nullable`. Here is good reference https://developer.apple.com/swift/blog/?id=25

**Comment by Zhukn1** [comment]
@joshuafeldman, thank you for this one. I agree that moving forward this should be done. I will try to make a PR in July.

**Comment by aaustin** [comment]
hey @joshuafeldman - Just an update here. The fact that params could be null in the failure case was an accidental edge case. In the last version, we made it so that `params` won't be null.

Making a separate task to add the `_Nullable` and `_Nonnull` to error and params respectively for the next version.

**Comment by ahmednawar** [comment]
@joshuafeldman our latest version of the SDK contains the right type annotations. Please check it out and let us know if you stumble upon any issues.
