### ISSUE TITLE
continueUserActivity always returns false

### ISSUE THREAD

**Issue by TimWatson** [BranchMetrics/ios-branch-deep-linking#402]
When opening a universal link `Branch.getInstance().continueUserActivity` always returns false. I use this check to know 1. Should I handle it myself, or 2. If my app can't handle it, open Safari. Right now this causes iOS to open the app, jump to safari, and then jump to the app store. If I remove `UIApplication.sharedApplication().openURL` it stays in the app and loads the correct deeplink but I need this as a fallback in case neither Branch nor my app can handle it. continueUserActivity should return true if it can handle it so I know not to redirect to Safari.
 
The link I'm using is http://radpad.co/ABVl/z0abg2sfBv and I'm on version 0.12.5

```
func application(application: UIApplication, continueUserActivity userActivity: NSUserActivity, restorationHandler: ([AnyObject]?) -> Void) -> Bool {
		let handledByBranch = Branch.getInstance().continueUserActivity(userActivity)
		if handledByBranch {
			return handledByBranch
		} else if userActivity.activityType == NSUserActivityTypeBrowsingWeb, let webpageURL = userActivity.webpageURL {
			UIApplication.sharedApplication().openURL(webpageURL)
		}
		return false
}
```

**Comment by ahmednawar** [comment]
@TimWatson the method is returning false because it can't determine with 100% certainty whether the link, before sending the request, would be handled by Branch. The SDK logic checks client-side based on a list of whitelisted domains that includes Branch's domains(bnc.lt, app.link, and test-app.link) by default. However, your link would still deep link correctly since we also check for your domain server-side but the method would return false. In order to whitelist your domain on the SDK to get true for your links, please follow the steps here outline here: https://dev.branch.io/getting-started/universal-app-links/advanced/ios/#custom-continueuseractivity-configuration

Hope this helps! Let me know if you have any questions.

**Comment by TimWatson** [comment]
That did it thanks @ahmednawar!
