### ISSUE TITLE
Question about facebook share link (og tags)

### ISSUE THREAD

**Issue by rt2zz** [BranchMetrics/ios-branch-deep-linking#510]
See issue here: https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/57#issue-190772838

User is invoking showShareSheet and inspecting the resulting link in facebook link debugger. Debugger is requesting the `og:*` tags be explicitly defined.

My suspicion is that the branch sdk should be doing an automatic mapping of title -> og:title image -> og:image etc. Please correct me if I am wrong, or if this functionality is already supported what changes may be required in the showShareSheet invocation to trigger setting these tags.

**Comment by E-B-Smith** [comment]
There's nothing in the SDK that creates the `og:*` tags.  Those are created by the Branch back end as a service so that Facebook (and others) can scape things like the `og:title` when they create a description for a web page for link.

The `$fallback_url` takes precedence over anything set in the share sheet.

Try removing the `$fallback_url` parameter and try again.

**Comment by aaustin** [comment]
@rt2zz Answered in the RN thread. Closing out here.

**Comment by rt2zz** [comment]
thanks @aaustin & @E-B-Smith 👍
