### ISSUE TITLE
Functional testing / UITests  - branch configuration

### ISSUE THREAD

**Issue by CurlyHeir** [BranchMetrics/ios-branch-deep-linking#574]
I would like to test if app behaves well, when opened from deeplink.

Our app strongly relays on deeplinks, testing that isn't easy job. Instead of wrapping branch SDK and do some tricky stuff in dependency container, I'd like to setup branch with different url (mock server for instance, like WireMock). 

What do you thing about this idea? should i make feature request or just pull request?

**Comment by E-B-Smith** [comment]
I know this is hard to test because I test this all the time! 

Do you simply want to change the Branch API URL at runtime?  

I can add an option to set the Branch API URL in the app's info.plist.  When the SDK initializes it can check the info.plist for a Branch Server API URL.  If it's set, it will use that URL, otherwise it will fall back to the default Branch URL.

**Comment by CurlyHeir** [comment]
Yes, i'd like to have possibility of configuration in runtime, literally i want to have possibility to simulate app opening from _deeplink_. 
My entire flow: 
1) In applicationDidFinishLaunchingWithOptions i injected parameters passed from _UITests_ via _LaunchArguments_ and _LaunchEnvironment._. I created another implementation of AppDelegateProtocol for UITests, that is added only to target that UITests depends on, so i can freely configure pretty much everything in app depending on passed configuration.
2) For now i added category for _BNCPreferenceHelper_ that overrides `- (NSString *)getAPIBaseURL`, implementation of that method catches launch arguments and check if should configure branch with different URL.  
3) provided URL points to WireMock server, and there are some hardcoded branch responses. 
(still working with that one) 

 Your proposition definitely looks good, but it lack of flexibility. Not in every single test we want to stub branch. Probably for tens of test cases i'd use two or three mock server endpoints ( due to  request matching limitations)

So how about creating `BNCPreferences` class, that is optional configuration that can be setup in runtime? didFinishLaunchingWithOptions is really good place for tests. There are any limitations why we can't do it like that?

**Comment by E-B-Smith** [comment]
How about I simply add the method `- (void)  setAPIBaseURL:(NSString*)baseURL` to the preference helper?

**Comment by CurlyHeir** [comment]
if that will work out then why not? something like 
```[[BNCPreferenceHelper preferenceHelper] setAPIBaseURL: @"example_url"];```
looks harmless and convenient 👍

**Comment by E-B-Smith** [comment]
I added the property `branchAPIURL` to `[BNCPreferenceHelper preferenceHelper]` so that the Branch API URL can be set for testing.

This fix is available now on the `beta` branch of the Branch iOS SDK repo and will be merged to the master branch after more testing and feedback.

Here is some information about the `beta` branch and our beta program in general: [Branch beta program.](https://branch.app.link/Beta-Info)
