### ISSUE TITLE
Test key not being used even with setDebug 

### ISSUE THREAD

**Issue by brunolemos** [BranchMetrics/ios-branch-deep-linking#640]
### Even after calling setDebug:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [RNBranch setDebug];
  [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];
```

### And configuring the test key:

![image](https://user-images.githubusercontent.com/619186/27418646-d0aa79f6-56f2-11e7-8fd5-d289b786f23d.png)

### Only the live key is loaded

![image](https://user-images.githubusercontent.com/619186/27418669-039376b0-56f3-11e7-8f60-b5261cd2206f.png)

Am I doing anything wrong or is this a bug?

**Comment by E-B-Smith** [comment]
Yes, you're doing it wrong.  But only because we made it hard to do it right.

To test using the test key, delete the `branch_key` dictionary.

Then add back a `branch_key` with just the `key_test...` as a string value.

Remember to change `branch_key` to the `key_live...` for production!

I've been meaning to make this easier and saner for a while.  I'll do that this afternoon.

Sorry for the confusion!

**Comment by brunolemos** [comment]
The most intuitive way for me is for it to use the test key if I used `setDebug` and the live key if not. This way I don;t need to "remember to change to production", it will just work for both debug and release.

`AppDelegate.m`
```
#ifdef DEBUG
  [RNBranch setDebug];
#endif
```

`RNBranch`
`if setDebug then testKey else liveKey`

**Comment by jdee** [comment]
It looks like you're using the react-native-branch SDK. You also need to call `[RNBranch useTestInstance]` before calling anything else, i.e.:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#ifdef DEBUG
  [RNBranch useTestInstance];
  [RNBranch setDebug];
#endif // DEBUG

  [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];
```

The `setDebug` method just determines whether the SDK will simulate install events, not whether the test instance is used.

We recently introduced support for an optional `branch.json` file to control these things in the `react-native-branch` repo. See https://rnbranch.app.link/branch-json for details. You can choose the test instance there instead of native code. That will be released soon.

**Comment by brunolemos** [comment]
@jdee Got it, thanks.
