### ISSUE TITLE
Universal Links only works through safari . it does not work from gmail app or mail app ios.

### ISSUE THREAD

**Issue by zeeshansuleman** [BranchMetrics/ios-branch-deep-linking#778]

**Comment by E-B-Smith** [comment]
I tested this in Chrome and the mail app and it works for me on iOS 10.0 and 11.0.

Do you think it could be related to issue #766, where universal links sometimes don't work on 11.0 devices?

Otherwise, send me some more details of how this doesn't work so that I can debug this.  It's a terrible user experience to not have links work.

**Comment by zeeshansuleman** [comment]
@E-B-Smith Thanks for your response. Let me provide you the detail of the use case..
working use case : when i signin through my gmail account on safari and open the link from there , it opens the app successfully.
Error Use case: When i do the same but use gmail or mail app of iphone , upon clicking the click it prompt me to open store rather than redirecting me to the app.plz see the screen shot.
![img_0013](https://user-images.githubusercontent.com/12757747/35550763-b7684418-05ad-11e8-8dbd-0e4aaa72d323.jpg)

**Comment by E-B-Smith** [comment]
It looks like you're trying to handle Branch deep linked email, which can be tricky to set up.

Please contact integrations@branch.io and they can help you get this going.  If you already have a technical account manager then contact them directly. They will be happy to help and will already know your specific use case.
