### ISSUE TITLE
Strange Fabric dependency and header import

### ISSUE THREAD

**Issue by a56097634a** [BranchMetrics/ios-branch-deep-linking#842]
Hello Branch Engineers,

I noticed in the SDK, there are several strange header imports such as: `#import "../Fabric/Answers.h"` or `#import "../Fabric/Fabric+FABKits.h"`.

I checked the podspecs, it has Fabric header files included in the source files like: `"Branch-SDK/Fabric/*.h"` and subspecs with: `core.private_header_files = "Branch-SDK/Fabric/*.h"`

I am wondering what is the reason that you guys choose not to add Fabric explicitly in the podspec (which is how I approach adding dependencies) but choose to do header imports, if you have dependency on it. In my opinion, referencing dependency (Fabric) through a relative path and bundling the headers in the podspec happens to work today but could easily break in future CocoaPods releases.

P.S: We are pretty strict on these type of things with some additional checks in the CI configuration on our end. Thats how I noticed this issue.

Thanks in advance,

**Comment by E-B-Smith** [comment]
We added Fabric as an optional dependency.  If you include Fabric in your project, Branch will link to Fabric Answers for install/open stats, and add version information for Crashlytics.

Some of the apparently weird way the headers and dependencies work in Branch is because the SDK is designed to be installed through either Fabric, Cocoapods, Carthage, or as a direct dependency.

It's seems odd but it works and it's been refined through a lot of use.

If it breaks for you let me know!  Obviously we've done a lot of work to make sure installing and using Branch is easy and flexible, so I'll we'll do our best to fix it.

**Comment by justinseanmartin** [comment]
For consumption via CocoaPods, could you include the Answers integration as a subspec that can be optionally included (and actually has a dependency on Fabric) instead of relying on optional binding?

Alternatively, you could just privately redefine `+[Fabric configurationDictionaryForKitClass]` and `ANSLogCustomEvent` within `BNCFabricAnswers.m` in order to keep that as a private concern.

It is mostly a concern for us in the context of using the relative path imports. We have a workaround in our code, but would be nice to remove it eventually.

**Comment by E-B-Smith** [comment]
Are you using CocoaPods to manage your dependencies?

**Comment by justinseanmartin** [comment]
Yep, we use CocoaPods to manage our dependencies. We have added a whitelist to our linter that validates source files that we compile and their header imports. 

Generally, we'd just import these as `#import "Fabric+FABKits.h"` for imports of headers shipped within its own library. 

I understand that this is an extenuating circumstance in that you're shipping the Fabric headers as part of your framework, even if they're marked as "Private" (which isn't the same as "Project"). 

If Fabric makes a breaking change in their API that you're using, it'll break your library. For this reason, I'd recommend having an optional subspec that brings a dependency on Answers and optimistically locks to some minor version of Answers podspec. That way, the Answers integration in Branch can be optional to the consumer and you can use imports as `#import <Answers/Answers.h>` when it is enabled as you'd normally expect.

**Comment by E-B-Smith** [comment]
We are a partner with Fabric! We added that header specifically so that their SDK kit manager could distribute our SDK.  Hopefully they tell us before publishing a change that breaks their app kit manager.

https://fabric.io/kits/ios/branch/summary

**Comment by justinseanmartin** [comment]
That may be true, however it will mean that both Branch and Fabric dependencies will need to both be updated in our project if a breaking change is introduced. There is nothing in the Branch podspec that indicates which version(s) of Fabric are able to be used together.
