### ISSUE TITLE
DeepLink callback in not firing until the app goes to background

### ISSUE THREAD

**Issue by asiliuk** [BranchMetrics/ios-branch-deep-linking#843]
Hi, I'm stuck with similar issue like this onehttps://github.com/BranchMetrics/ios-branch-deep-linking/issues/825

But only in my case changing URL schemes order didn't help.
Issue can be reproduced even on test project https://github.com/BranchMetrics/Branch-Example-Deep-Linking-Branchster-iOS

So when I'm trying to open my custom app URL when app is in foreground nothing happens until goin into background and back again

## Steps to reproduce
* open app scheme url (for example my_app://open/screen) and app is in foreground
* for example link is opened by [[UIApplication sharedApplication] openURL:...] from app

**nothing happens** and callback isn't called

* go in background (press home button)
* and in foreground again

 **callback gets called** and everything is okay

Hope you can help me with this

**Comment by budged** [comment]
Seems like I found possible issue in source code in **Branch.m** file

`
- (BOOL)handleSchemeDeepLink_private:(NSURL*)url fromSelf:(BOOL)isFromSelf {
    ....
    [self initUserSessionAndCallCallback:**!**self.isInitialized];
    ....
}

- (void)initUserSessionAndCallCallback:(BOOL)callCallback {
    ....
        // If the session is not yet initialized
    if (**!**self.isInitialized) {
        [self initializeSession];
    }
    // If the session was initialized, but callCallback was specified, do so.
    else if (callCallback) {
        ....
    }
}
`
So, when session is initialized both cases fail, so seems like `else if (callCallback)` can't be reached from deeplink handling code, because:
* Session is NOT initialized, then callCallback argument is false and nothing is called
* Session is initialized, then fall in first condition and else part never called

So probably it should be `[self initUserSessionAndCallCallback:self.isInitialized];` in first place? without !

**Comment by E-B-Smith** [comment]
Branch opens use app schemes as a way to support opening universal links.

The expected way for Branch links to work is:

1. User clicks on a link like 'https://myapp.app.link/xyzpdq'.

2. Either the app opens immediately and handles the link (universal link).

3. Or Safari opens a web page at 'https://myapp.app.link/xyzpdq', which in turn tries to open the app with an app scheme that looks like 'myapp-scheme://open?link_click_id=348527481794276288'  (uri-redirect mode).

4. In the case of #3, the app opens with URL 'myapp-scheme://open?link_click_id=348527481794276288'.  The Branch SDK sends 'myapp-scheme://open?link_click_id=348527481794276288' to the server, and the server figures out, hey, 'myapp-scheme://open?link_click_id=348527481794276288' maps to 'https://myapp.app.link/xyzpdq', and sends back the data for 'https://myapp.app.link/xyzpdq'.

5. If an app opens a link like 'myapp-scheme://open/something' (it doesn't have the link_click_id part), the Branch SDK looks at it and thinks, nope, that's not ours, and ignores it.  

Does this clear up what might be going on?

**Comment by E-B-Smith** [comment]
I hope you resolved you issue! If you're still having trouble please reopen this issue or open another.
