### ISSUE TITLE
iOS - Referral events not getting tracked on dashboard and universal link not working (intermittently)

### ISSUE THREAD

**Issue by amritasinghbg-e** [BranchMetrics/ios-branch-deep-linking#897]
Once the link is shared from my app through WhatsApp or sms, if I go back and click on the same link, some times deep-linking fails and the download link opens again. The same issue is faced by the user who installs the app from that link. 

Also, whenever the link is shared from an iOS device, to an iOS or Android device, and the receiver installs, the event is not getting tracked on branch dashboard. 

Please help!

Thanks,
Amrita

**Comment by E-B-Smith** [comment]
> Once the link is shared from my app through WhatsApp or sms, if I go back and click on the same 
> link, some times deep-linking fails and the download link opens again. The same issue is faced by 
> the user who installs the app from that link.

I think this issue is likely related to the known issue with Apple not downloading the Apple App Site Association file to the phone sometimes.  The AASA file tells iOS to open an app rather than a website.

[Here's a write up of the issue, which unfortunately Apple still hasn't fixed yet.](https://github.com/BranchMetrics/ios-branch-deep-linking/issues/766)

> Also, whenever the link is shared from an iOS device, to an iOS or Android device, and the receiver 
> installs, the event is not getting tracked on branch dashboard.

The referrals should just work.

The referrals work like this: 

1. An existing user shares a Branch link with a someone who doesn't have the app.
1. The person who doesn't have the app clicks the link, installs and opens the app.
1. That's one referral. The referee must be a fresh install, not a reinstall.

The last part may be tripping you up if you are testing.  To test this, uninstall the app from the device and reset the advertising identifier on the phone and try the test again. 

Let me know if you continue to have problems.

**Comment by amritasinghbg-e** [comment]
Thank you @E-B-Smith! I tried resetting the advertising identifier and it's working - I should've considered the aspects of fresh and re-installs.

Thanks,
Amrita
